### ISSUE TITLE
build fail?

### ISSUE THREAD

**Issue by im-coder-lg** [DylanGTech/Playerdom#1]
I ran the server command and it worked there. Now, if I run the client command which is `dotnet run --project Playerdom.OpenGL\Playerdom.OpenGL.csproj`, it says that build has failed. Can you please check this?(I run Win 7 and have .Net 6 preview installed)

**Comment by DylanGTech** [comment]
Hello. Could you provide the output you get in the console? In particular anything about the build error? Are you sure you are running the program from inside the directory you extracted the program from?

I did just now fix an issue related to running the client inside any directory, so make sure you update the project using "git pull", or clone the project  again before trying.

**Comment by im-coder-lg** [comment]
I am sure I ran the project from it's root directory. But I didn't clone it. I will clone it today.

**Comment by im-coder-lg** [comment]
![image](https://user-images.githubusercontent.com/76845820/118384417-77813880-b623-11eb-95c9-63d192fe3e13.png)
The error. I cloned the repo using Git, but no dice.

**Comment by im-coder-lg** [comment]
Wait a minute, where did you solve your issue?

**Comment by DylanGTech** [comment]
I looked into these types of errors, and I found that this is a common problem with building MonoGame. The issue appears to be caused by MonoGame's dependency on FreeType6.dll. There isn't much I can do other then advise people install them in the README.

Try installing the MGCB Pipeline tool via these commands:
`dotnet tool install --global dotnet-mgcb-editor`
`mgcb-editor --register`

If this does not resolve the issue, then the dll wasn't installed, and you'll have to install it yourself from Microsoft, through this link: https://www.microsoft.com/en-us/download/details.aspx?id=30679

Let me know if it works!

**Comment by im-coder-lg** [comment]
no dice

**Comment by im-coder-lg** [comment]
I got the DLL, but no dice

**Comment by DylanGTech** [comment]
The only such issue I can find is with MonoGame itself.
https://github.com/MonoGame/MonoGame/issues/7172

To be clear, are your machine AND the installed .NET 6 Preview SDK 64-bit?

**Comment by im-coder-lg** [comment]
Yep, damn clearly, I got .NET 6 preview as SDK.

**Comment by coder-lg** [comment]
Yep, damn clearly, I got .NET 6 preview as SDK.

**Comment by im-coder-lg** [comment]
and its 64 bit

**Comment by im-coder-lg** [comment]
closing as no response/no idea here

**Comment by DylanGTech** [comment]
After looking into this issue, I actually have a solution for a temporary workaround. It is mentioned in the README on the old project, some people have an issue with a missing dll file (freetype6.dll) that has been a persistent issue with the MonoGame engine for years now.

I have found a link to it. To confirm this is your issue, run instead with `dotnet run --project Playerdom.OpenGL\Playerdom.OpenGL.csproj --debug`. If you get any specific errors about a missing DLL or FreeType, that's the culprit.

I looked for a way to make this work without installing Visual Studio. It is more than possible, but you will need to either install the Visual C++ 2012 and 2013 SDKs, or build Freetype6.dll from source, and put it in the correct folder.
More info here: https://community.monogame.net/t/monogame-noob-unable-to-load-freeimage/6255/8


It's a rather precarious situation. I will have to re-add the warning to this repo about this issue until MonoGame engine devs find a way to fix it so it just works with the CLI on its own. I may add a script that does the workaround automatically.

**Comment by im-coder-lg** [comment]
Alright @DylanGTech testing this soon! Thanks!

**Comment by DylanGTech** [comment]
Any updates on this? If not, I'll close it for now.

**Comment by im-coder-lg** [comment]
Well, I don't have any updates so close this, I possibly can't get the required modules for this on a Windows 7 PC.
